# Site
name: 'Trending source'
description: 'News and Events'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: "https://trendingsource.github.io" # the base hostname & protocol for your site, e.g. https://example.com
# baseurl: '/'
disqus: 'trendingsource'
email: 'trendingsource@gmail.com'

include: ["_pages"]
permalink: /:title/
# permalink: /:name/
# Plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jekyll-gensocial
authors:
    ngoc:
      name:           Ngoc
      site:           https://trendingsource.github.io/index.html
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am ngoc, the Blog Editor of \"Trending source\", the the site you're currently previewing. I hope you like it!"
      email:          trendingsource@gmail.com
      twitter:        https://twitter.com/trendingsource

    hanna:
      name:           Hanna
      site:           https://trendingsource.github.io/index.html
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          citylodge.org@gmail.com
      twitter:        https://twitter.com/trendingsource

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ngoc
      avatar: assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

#gensocial config
jekyll-gensocial:     # These are the default settings
  enabled: true       # Disables the output
  size:               # The size of the overall canvas
    width: 1920
    height: 1080
  background:         # The background image
    path: nil
  text:
    string: nil       # Overrides the post/page title
    font_path: nil    # Path to your custom font
    pointsize: 100    # Font size
    fill: "#000000"   # Font color
    rect:             # Text will appear inside this frame
      size:
        width: 1600
        height: 500
      origin:
        x: 150
        y: 100


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
